### ISSUE TITLE
Lockpicking Cars and Doors of houses

### ISSUE THREAD

**Issue by Shanvir13** [ScottUK/ladojrp-issues#109]
I want to request a feature, which will bring so much more RP for the illegal side, and for the legal side. Lockpicking. And I don't mean only lockpicking cars I also means doors, as of houses of buildings. This will bring so much more RP to the server in my opinion. Not only for revenge on others but lockpicking into houses to steal stuff, do research on someone. Lockpick cars, if they haven't payed there monthly bill, or they stole the car, and you are repo'ing it back for a private company or dealer.

Something along the lines of this, this here is a mod for lockpicking.
https://www.gta5-mods.com/scripts/lock-picking

Check it out for reference but please please consider this as it can bring for so many more RP scenarios and it can also support your server as in more people will play and like the server.

**Comment by LadojrpAustin** [comment]
Hello Shanvir13, This is Austin with the LADOJRP Suggestions team - We would like to thank you for your suggestion and it will be read over very carefully.


This would be a great addition to the server, but there is no point for lock picking a house since there is nothing you can technically store at the house, but the vehicle locking picking sounds like a great idea. I will pass this to our head of suggestions team.

- Administrator Austin

**Comment by Shanvir13** [comment]
Thank you sir I appreciate the time you took to reply I wish there was
hours lockpicking but that would need further updating like placeble
furniture and stuff yk?

**Comment by LADOJRP-Mello** [comment]
As Much as I love the idea, I don't think this would work in a VMENU Server. This is a great ESX Idea but definitely will not be used as much in VMenu

Your idea for houses can cause issues with people who spent money to own houses, which can sometimes be stated as "unfair" to further addon you can always roleplay with /mes with lockpicking as all houses are not locked, and majority of them are teleport blips.

Thank you for your suggestion!
