### ISSUE TITLE
Badge flash suggestion

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#14]
In LAPD we have a policy that you can open carry of duty and not in uniform and that you must have a badge on you at all times (Cannot be visible we need to rp it's in a pocket or something) so I think this https://www.lcpdfr.com/downloads/gta5mods/character/23396-lapd-badge-for-042/ would improve the rp and be a cool feature.

**Comment by LadojrpAustin** [comment]
Hello Bright this is Austin with the LADOJRP Suggestions team

Thank you for this suggestion and this will be read very carefully and taken under consideration

Sadly this will be denied because there is really no point in adding this since you can just do /me takes badge out pocket and shows.

We have the /me script to RP scenarios we really cannot do so I recommend just doing /me from now on.

Administrator, Austin
