### ISSUE TITLE
Rules overviewed/ reworked

### ISSUE THREAD

**Issue by Rubenv24** [ScottUK/ladojrp-issues#25]
Why do us donators get all these weapons/throwables like bombs and shit but we aren't allowed to use them? I was wondering if maybe I Can suggest for them to redo some rules? For the no hit man rp rule is pretty dumb in my opinion.. People ask for different rp's but we are very limited to rps that we can do... if we want to bomb something we cant since no bomb rp is allowed.... We aren't allowed to impersonate leo and i get why, But maybe edit these rules just a bit... For example some other rules no child rp.. child rp can bring so much rp  for example, a lost child, a child who was abandoned it can give leo so much rp but we can't do it... This is why I think there are always constant 10-80's / shoot outs, another rp that is against the rules.. The no revenge rp rule is pretty dumb in my opinion for example irl, somebody kills your brother and you know said person who killed your brother in rp but you cant do shit about it cause the no revenge rp rule... Its a pretty unrealistic rule in my opinions, then we have the no stalking rp rule nothing wrong with it at all... Stalking happens irl why cant it happen in game? Those are some of the rules I believe should be updated.

**Comment by WiredOrange** [comment]
As I enjoy playing devil's advocate, let's break this down and think on the administration side. You have to think about not the good side of things that can happen, but the bad side, and which are more likely to happen as we are a non-whitelist server

Firstly let's talk about the weapons. I do see your point here but this does allow the donators to use these weapons in specifically request scenarios. In the terms of everyday use, yes they are a bit deceiving but for a good RP, they can be used properly.

Secondly lets talk about hitman rp. This is mostly banned, unless approved or you and the other RP have been planned or understand each other a lot. Hitman RP is annoying because if I decide to "hire" a hit man and then just go and shoot this person because they overtook me on a yellow line, it seems unreasonable. You can simply say "well I hate when people do that"
 which is not true and overexaggerated. The issue with hitman is it doesn't incite good RP, just simply RDM
 
 Next lets talk about children RP. this one is sad because you are right, it could be awesome RP but sadly the people that abuse it out weight the people that use it for good. I won't go into the major details but things can get inappropriate very quickly. It is much easier to just stay away from the entire scene of children, especially because a decent amount of people playing on here are children. 
 
 I don't know what you mean by no revenge rule as it is not in the [rules](https://docs.google.com/document/d/1pdnvjb8nvjd17G9hHD0Py78sAcZDbYTAAZTs3dExFNo/edit)... 
 
 I'm am unsure what the reason behind the stalking rule is but I can assume that it has been an issue in the past and it can cause issues. It can get very very annoying as cops actually deal with this all the time. I am always being followed/stalked/targeted as a cop. The "Whats your badge number"/"Better watch out officer, I'm coming for you" gets really old really really fast because everyone does it because they think they are cool and gonna do a dope rp but instead it just because a stupid shootout.

**Comment by ladojrp-alopez** [comment]
Hello, this is Lopez, overseeing the suggestions that get placed for the community of Los Angeles Department of Justice Roleplay, 

The suggestion you have suggested has been talked about these past few days, and sad to say, it will be denied. Reason being, you can always get executive approval for role play within bombs, hitman role play, and much more. These rules are placed to minimize the quality role play a player wishes. Having this rule for everyone to do, will not only advert more killings, but the idea of passive role play.

-LADOJRP Suggestions Team
