### ISSUE TITLE
A kick system where it prevents you from joining for a certain amount of time.

### ISSUE THREAD

**Issue by Green5tar1** [ScottUK/ladojrp-issues#30]
I remember playing on a server once and they had this system where if you got kicked it would prevent you from rejoining for 5/10 mins, so kind of like a mini ban that would only show up as a kick. I think this would be a good system to have in place as it would mean that there was more to a kick and that you couldn't just instantly relog afterwards like nothing had happened.

**Comment by ladojrp-alopez** [comment]
Hello, this is Lopez, overseeing the suggestions that get placed for the community of Los Angeles Department of Justice Roleplay,

The suggestion you have requested will be denied. Adding this will kill the player count for those who receive the kick punishment. They have the discretion to come back if they wish to do so. It is on there record so, our staff team is enforced to ensure before punishing someone, they must check for any prior offenses. Having the 5-10 minute wait system would not fix anything, or prevent any server violations caused by the community its self.

- LADOJRP Suggestions Team
